CFLAGS=-Wall -g
CC=cc

all: ex1 ex3 ex5 ex6 ex7 ex8

ex1:
	$(CC) $(CFLAGS) ex1.c -o ex1

ex3:
	$(CC) $(CFLAGS) ex3.c -o ex3

ex5:
	$(CC) $(CFLAGS) ex5.c -o ex5

ex6:
	$(CC) $(CFLAGS) ex6.c -o ex6

ex7:
	$(CC) $(CFLAGS) ex7.c -o ex7

ex8:
	$(CC) $(CFLAGS) ex8.c -o ex8

clean:
	rm -f ex1
	rm -f ex3
	rm -f ex5
	rm -f ex6
	rm -f ex7
	rm -f ex8
